### ISSUE TITLE
Scaffolding executable should create minimal Gemfile

### ISSUE THREAD

**Issue by nskins** [nskins/goby#127]
When somebody runs our executable `goby`, it creates a simple project. It includes a .gitignore, so it would be nice to also include a Gemfile with the following content:

```ruby
`source 'https://rubygems.org'

gem 'goby'
```

Make the pull against the `0.2.1` branch.

**Comment by Jeff-Hostetler** [comment]
I have a pull for this unless you'd rather some contributing for the first time

**Comment by nskins** [comment]
Hi @Jeff-Hostetler. Yeah, I would prefer a first-time contributor to take this one. Thanks though!

**Comment by virtual-monk** [comment]
Can I have this one assigned to me?

**Comment by nskins** [comment]
Yes!

**Comment by nskins** [comment]
Resolved in #131.
