### ISSUE TITLE
Tile description should not add newlines to the end

### ISSUE THREAD

**Issue by nskins** [nskins/goby#128]
In `#describe_tile` of `world_command.rb`, the output of the `Tile`'s description is automatically appended with two newlines, but this is the only place in the framework where it's done. Users probably won't expect or like that. Just remove the two newlines and update the scaffold project to include newlines in the `Grass` description. You should also make sure a `Tile` with no description does not display extraneous newlines.

Make the pull against the `0.2.1` branch.

**Comment by pokharelonrails** [comment]
@nskins can I take a look?

**Comment by nskins** [comment]
@pokharelonrails Yes, of course!

**Comment by Hedion** [comment]
@nskins I would like to give it a crack at the ol' bat. Unless it was already solved by @pokharelonrails

**Comment by nskins** [comment]
Hi @Hedion. Sorry, this issue isn't open right now since I haven't had a chance to review the pull request from @pokharelonrails. Thanks for your interest, and please stay tuned for more opportunities to contribute!

**Comment by nskins** [comment]
Closed by #130.
