### ISSUE TITLE
Helpful text after eating food

### ISSUE THREAD

**Issue by nskins** [nskins/goby#13]
The amount of HP recovered should be nicely displayed after the entity eats some food.

A good formatting will display (1) the entity's name, (2) the food's name, and (3) the amount of HP recovered, such as: "Player1 uses Donut and recovers 7 HP!"

Additionally, the next line might show the current HP (divided by max HP) as: "HP: 92.5/100"

Other formats are also acceptable.

**Comment by ryanflach** [comment]
@nskins Will be working on this in the next day or so.
