### ISSUE TITLE
Instructions when starting the game

### ISSUE THREAD

**Issue by sallymacnicholas** [nskins/goby#16]
I started playing the example game and the first thing I noticed was that there were no instructions on how to play. I think you can kind of figure out how to play, but it would be nice to know before you start playing. 

I like that when you type in "help", that all the default commands are brought up. I think it would be helpful if when you started the game that it 1) Shows you the default commands and 2) Tells you the point of the game and 3) Give a description of all the things like HP, Attack and Defense. Also, quit should be added to the default commands.

**Comment by nskins** [comment]
Hi Sally, I agree - it is especially important that the preset game displays that helpful information you suggested. This is a content-specific feature so it serves as a great example for how the framework's users can set and call long blocks of text. I'll take care of this. Thanks!
