### ISSUE TITLE
Agility attribute for Entity & Battles

### ISSUE THREAD

**Issue by nskins** [nskins/goby#21]
We should implement the agility member variable for Entity. Agility will be used to determine who goes first during a turn. Possible algorithm:
1. sum = player.agility + monster.agility
2. Choose a random number from 0 to (sum - 1).
3. If the number < player.agility, then player goes first. Otherwise, monster goes first.

Such an algorithm uses the ratio to decide who goes first. Additionally, there is a more equal playing field since it is not guaranteed that the one with higher agility will always go first.

It will also be important to provide a test suite for this new attribute.

**Comment by DanDobrick** [comment]
I can try to implement this.

**Comment by DanDobrick** [comment]
PR here:  #41 
I'm not too happy with how non-DRY the code is, but this is a working implementation of the agility attribute.

I would like to DRY it up, but I think that would require some large refactoring of the `battle` method (such as taking it out of the `Player` class and putting it in a module or something) I would be willing to do that, but I wanted to make sure that's what you wanted first.

If I am to refactor the `battle` method out, I was hoping you could point me to where it's being called so I can ensure it works as intended.

**Comment by nskins** [comment]
Nice work! Here are some notes:

- The agility variable should have a role during every turn of battle. After the player and monster both select an attack, then calculate the order and play it out appropriately.
- Now that you mention it, I've always thought it would be nice to have the battle method abstracted into Entity so that potentially Player could face Player or Monster could face Monster. Not sure if it's exactly what you're aiming for, but you're welcome to refactor the method into a module or however you're thinking. The `battle(Monster)` function is called on line 108 of player.rb.

**Comment by DanDobrick** [comment]
Updated the battle loop so the agility variable determines who attacks first each turn. 

If this PR is good to go, I suggest merging it and opening a new issue for refactoring.

**Comment by nskins** [comment]
@DanDobrick let's continue this discussion on #41.
