### ISSUE TITLE
Update Entity function "print_status"

### ISSUE THREAD

**Issue by nskins** [nskins/goby#24]
Initially, the only available subclasses of Equippable were Weapon and Helmet. After fixing issue #20, we now have Shield, Torso, and Legs.

The "print_status" function of Entity should be updated to display the names of those new subclasses and the currently equipped item (in a similar fashion to Weapon and Helmet).

**Comment by flpcury** [comment]
Hey, I can do that! Hahahah
Actually, I'm ready to submit a pull request.
I'm a total beginner in coding and in git, so I'm really sorry if I'm doing something wrong.
