### ISSUE TITLE
Randomize attack damage

### ISSUE THREAD

**Issue by nskins** [nskins/goby#28]
Currently, the amount of attack damage done in battle is deterministic.

There should be a random element in the calculation to spice things up.

**Comment by JupiterLikeThePlanet** [comment]
I'm currently working on this, but wanted to clarify something. 

In attack.rb,  I initially understood user.attack to be the attack damage until I came across this line of code:  enemy.hp -= (@damage * multiplier).round(0)

What is user.attack supposed to represent in the line "multiplier = 1 - ((enemy.defense * 0.1) - (user.attack * 0.1))"

**Comment by nskins** [comment]
@JupiterLikeThePlanet The "@damage" attribute refers to the power of the "Attack" itself. And "user.attack" refers to the attack stat of the "Entity." Basically, we are trying to use both the power of the Attack (@damage) and the Entity's stats (user.attack) as factors into calculating the HP that's subtracted from the enemy's health. 

Hope that helps and please follow up if I can assist you further.
