### ISSUE TITLE
Case-insensitive world commands

### ISSUE THREAD

**Issue by nskins** [nskins/goby#45]
When the player is on the world map, commands should be interpreted case-insensitively. Change the function `interpret_command` in `lib/world_command.rb` so that each command is interpreted case-insensitively. 

Use the `casecmp` function of `String`. Also, it may be necessary to change from using switch-case statements to if-else statements.

**Comment by BrianHGrant** [comment]
Hi, I came across this issue and wanted to help work on it. I believe I have made all necessary changes to code, existing tests all pass, but am a little unsure of how to write any additional tests for my work as there is not an existing world_command spec. 

I am familiar with Rspec though, so if you had a psuedocode example of a test, I should be able to go from there.

**Comment by nskins** [comment]
The tests for `interpret_command` should test each command (both lowercase and otherwise) and ensure that the appropriate operation is carried out on the `Player`. Since there is no existing file, I could open a separate issue about those tests.

Thank you for thinking about tests, though! Send a pull request whenever you're ready.
