### ISSUE TITLE
Replace movement commands with WASD

### ISSUE THREAD

**Issue by nskins** [nskins/goby#46]
https://en.wikipedia.org/wiki/Arrow_keys#WASD_keys

Replace the current movement commands (cardinal directions) with 'w', 'a', 's', 'd'.

W: up
A: left
S: down
D: right

In the `default_commands` method, change the descriptions to Unicode arrows.

Also, `print_possible_moves` should be changed to reflect the new style.

**Comment by FInGrayson** [comment]
nskins, I have fixed this issue. Here are the commits
612251fd4fdf2ccbcae4caa03dc908234f310d74 & 505303275aadc36e658e3f7c93fbdf5698225256.

I have created a pull request also.

**Comment by nskins** [comment]
Fixed in #47
