### ISSUE TITLE
New preset game

### ISSUE THREAD

**Issue by nskins** [nskins/goby#51]
The current preset game does not thoroughly show off the many features of the framework.

More battle commands for monsters, quests from NPCs, events, etc.

An hour of play time in the preset game should suffice in giving the user a thorough experience.

**Comment by gintavang** [comment]
Going to do this in order to get back into the swing of things with Ruby. It'll be based on the [Flaming Carrot](https://en.wikipedia.org/wiki/Flaming_Carrot_Comics) comic books.
