### ISSUE TITLE
Functions for positive & negative responses

### ISSUE THREAD

**Issue by nskins** [nskins/goby#53]
It would be nice to have two sets - one for positive responses and one for negative responses. These could be used for accepting user input on decision prompts (yes or no). Then there would be no need to list the options at the end of each prompt.

EDIT: see my response below for an updated implementation idea.

Send pull requests to the `y-n-responses` branch.

**Comment by rdavid1099** [comment]
@nskins I'm handling this while I work on #93. I just have a quick question, when you say global set of positive and negative responses, do you want those to be hard coded in player_input? Basically, I go ahead and call `player_input(return_string: true)` and then depending on whether the player states 'yes' or 'no', the player_input method returns a one of two responses or false if neither 'yes', 'no', 'y', or 'n' were entered. OR did you want it to be able to take in two different strings (ex. `player_input(return_string: true, positive: 'player said yes', negative: 'player said no')`) and return the appropriate response or false if neither 'yes' or 'no' were entered.

**Comment by nskins** [comment]
This issue doesn't actually involve altering `player_input`. I'm thinking that the implementation will extend the String class to provide two new functions: `is_positive?` and `is_negative?` Each function would have its corresponding set of responses hard-coded. I see now that these sets won't actually be global!

For #93, `player_input` should return whatever string the user entered; however there should be an argument that the string could be lowercased before being returned. The function signature might look something like this: `player_input(lowercase = true, prompt = '')`. If the input to `player_input(false)` is "YeS" then it would return "YeS". However, if we use `player_input`, then it would return "yes".

So the reason that I reference this issue in #93 is because the lowercase string can be hashed and checked for being a member of the chosen set (which only contains lowercase strings). Thus, I can check if "yes" is in the positive or negative set in O(1) time. More succinctly, we might choose to run `player_input.is_positive?` for these yes/no responses. 

With all that being said, I wouldn't worry about implementing both at the same time.
