### ISSUE TITLE
Argument in update_map

### ISSUE THREAD

**Issue by nskins** [nskins/goby#62]
We should allow `Player.update_map` to accept an argument of type Couple(Integer, Integer). This argument provides the y-x coordinates for around which Tile to update the 'seen' attribute on the Map. It should be fairly straightforward since the function implementation is the same - it just needs to accept that argument. See lib/Entity/player.rb. Include tests.

**Comment by nskins** [comment]
@rdavid1099, would you care to work on this?

**Comment by shyam12860** [comment]
Hi! Mind if I give this a shot?

Just to clarify my understanding of `Player.update_map`: would the usage of the accepted argument be in place of `@location`?

**Comment by nskins** [comment]
Hi @shyam12860, yes, please! And yeah, I believe that's what the change should be. Let me know if I can be of further assistance.

**Comment by shyam12860** [comment]
I thought it would be a good idea to assume the default argument is the player's @location, to keep existing calls to update_map intact. Let me know if you'd like anything done differently!
