### ISSUE TITLE
Use a different separator between each special command

### ISSUE THREAD

**Issue by nskins** [nskins/goby#64]
When showing special commands, use a different separator between each command. Currently, there are semicolons between each command. The code will be in `display_special_commands` which is located in lib/world_command.rb. 

Here are some example tests that you should add to ensure the correctness of the implementation:

When there's one NPC on the Tile (such as on Donut Field):

Change the old version:

`* Special commands: talk;`

to the following:

`* Special commands: talk`

Here's a better example for the use of the separtors, which can be found where the Shop and Hole on Donut Field are found:

`* Special commands: shop; dig;`

to the following:

`* Special commands: shop - dig`

or perhaps this:

`* Special commands: shop, dig`

Do whichever you think looks better.

There are some examples of using RSpec for checking output in spec/Entity/player_spec.rb. See the tests for `choose_attack` and `choose_item_and_on_whom.`

**Comment by rdavid1099** [comment]
Hey nskins, this seems like an interesting problem to tackle.  I'm going to fork this repo and see what I can do.

**Comment by rdavid1099** [comment]
PR made enhancing this feature.

Nice codebase.  I'd really enjoy doing more work with this project if you want to throw me some other issues.

**Comment by nskins** [comment]
Thank you. We'll keep in touch.
