### ISSUE TITLE
BattleCommand info should be absent for empty variable

### ISSUE THREAD

**Issue by nskins** [nskins/goby#78]
Change `Entity.print_status` so that `puts "Battle Commands:"` and the associated call to `print_battle_commands` are not executed when `Entity.battle_commands.empty?` is true. See lib/entity.rb.

**Comment by ryancoopersmith** [comment]
Hi I would like to help. This is my first open-source contribution and this seems perfect for me! I love text-RPGs. (Zork!) Working on it now...
