### ISSUE TITLE
Abstract all input into one function

### ISSUE THREAD

**Issue by nskins** [nskins/goby#93]
Currently, we use `player_input` (util.rb) for some user input, but we should use it for _all_ input. One argument for this function could be a boolean that, when set, would return a lowercase string (would be important for y/n questions, #53, etc.). Another argument would be the prompt, when required. For instance, on the world map, we use `>`. Also, sometimes there is no prompt. Include tests.

**Comment by hd719** [comment]
Hello there! I am new to open source and I would like to contribute to this project.

**Comment by nskins** [comment]
Hi @hd719, thanks for your interest! Would you like to work on this issue, in particular?

**Comment by rdavid1099** [comment]
Hey @nskins, sorry about going dark there for a bit, I had some things come up. I have more time now. If @hd719 isn't going to tackle this, I can take care of it. Otherwise, feel free to tag me in some issues and shovel some work my way.

**Comment by nskins** [comment]
Hey @rdavid1099, yes, you can work on this issue. Please send your pull request to the `player-input` branch and let me know if you have questions.

**Comment by hd719** [comment]
This issue is all yours @rdavid1099!

**Comment by rdavid1099** [comment]
Rock on. Thanks @hd719 and @nskins

**Comment by rdavid1099** [comment]
@nskins PR made for this issue.
