### ISSUE TITLE
Methods for certain sets of Integers

### ISSUE THREAD

**Issue by nskins** [nskins/goby#97]
We should write the following member functions for the `Integer` class:

- `positive?` : returns true if and only if the integer is greater than 0.
- `nonpositive?` : returns true if and only if the integer is not positive.
- `negative?` : returns true if and only if the integer is less than 0.
- `nonnegative?` : returns true if and only if the integer is not negative.

First, write tests in `spec/extension_spec.rb` for true & false examples of each of these functions. Next, the implementation can go in `lib/extension.rb`. Finally, search through the codebase for terms like '> 0', '>= 0', '< 0', and '<= 0' - replace each with its new corresponding function.

Pull requests for this issue can go to the `integer-ext` branch.

**Comment by jcreed** [comment]
i can do this

**Comment by morrme** [comment]
this was a good one--i was gonna make a go for it next!

**Comment by jcreed** [comment]
sorry about that one, i was thinking the same thing

**Comment by morrme** [comment]
@jcreed i understand! well done! 👍
